sudo: required
services:
 - docker
language: bash
script:
  # prepare qemu
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # build image
  - docker build -t guewen/rsync-raspbian .
  # push image
  - >
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      docker login -u="$DOCKER_USER" -p="$DOCKER_PASSWORD"
      TAG=$(grep "ENV SQUEEZEBOX_VERSION" Dockerfile | awk 'NF>1{print $NF}')
      docker tag guewen/rsync-raspbian guewen/rsync-raspbian:${TAG}
      docker push guewen/rsync-raspbian:${TAG}
      docker push guewen/rsync-raspbian
    fi

